apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-clusteip
  labels:
    app: {{ .Chart.Name }}-clusteip
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
